### ISSUE TITLE
Test2::V0 (or Test2::Bundle::Extended) exports a T() function which pollutes the user's namespace

### ISSUE THREAD

**Issue by djerius** [Test-More/Test2-Suite#125] opened 2017-06-22 19:40 UTC
`Test2::V0` exports a `T() `function which pollutes the namespace. 

```
% perl -MTest2::V0 -MData::Dumper -le 'print Dumper T()'
$VAR1 = bless( {
                 'operator' => 'TRUE()',
                 'code' => sub { "DUMMY" },
                 '_file' => '-e',
                 'name' => 'TRUE',
                 '_lines' => [
                               1
                             ]
               }, 'Test2::Compare::Custom' );
```

It breaks tests which happen to define a `T` package for testing purposes.  For example:

```
% perl -MTest2::V0 -e 'package T { sub new { return bless {}, shift } }; T->new'
Attempt to bless into a reference at [...]/lib/site_perl/5.22.1/Test2/Util/HashBase.pm line 75.
```

**Comment by exodist** [comment] 2017-06-22 19:45
The export is intentional, there by design. It has always been part of the extended/v0 bundle. Many many tests use this, and it is documented. I do not want to remove it, and doing so would break a lot.

To be using the bundle you are either writing a new test (in which case, avoid making that package name), or converting an old test, in which case this is far from the worst thing you need to handle during a conversion.

Closing, not a bug. However I will make a note in conversion docs.

**Closed by exodist** 2017-06-22 19:45 UTC

**Comment by djerius** [comment] 2017-06-22 20:12
I looked for documentation about T but couldn't find it.  Could you point me at it?

**Comment by exodist** [comment] 2017-06-22 20:15
https://metacpan.org/pod/Test2::Tools::Compare#QUICK-CHECKS

Note, it says not exportrd by default, but that is only when you manually load the tool. The bundle does load by default, intentionally.

**Comment by djerius** [comment] 2017-06-22 20:20
Ok, now I see it in the Test2::Bundle::Extended/Compare section, so it is documented at a more user friendly level.
